name: gameroom
description: A new Flutter project.
publish_to: 'Felipe Urbano'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.1.2
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  http: ^0.13.5
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/trophy.png
    - lib/assets/images/fire.png
    - lib/assets/images/placeholder.png
  #  - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
